2015-11-12 12:45:44.250 18587 INFO nova.openstack.common.periodic_task [-] Skipping periodic task _periodic_update_dns because its interval is negative
2015-11-12 12:45:44.258 18587 WARNING oslo_config.cfg [req-cea55508-0b77-4ec3-991c-5b88f0415666 - - - - -] Option "sql_connection" from group "DEFAULT" is deprecated. Use option "connection" from group "database".
2015-11-12 12:45:44.259 18587 WARNING oslo_config.cfg [req-cea55508-0b77-4ec3-991c-5b88f0415666 - - - - -] Option "lock_path" from group "DEFAULT" is deprecated. Use option "lock_path" from group "oslo_concurrency".
2015-11-12 12:45:44.260 18587 WARNING oslo_config.cfg [req-cea55508-0b77-4ec3-991c-5b88f0415666 - - - - -] Option "url_timeout" from group "neutron" is deprecated. Use option "timeout" from group "neutron".
2015-11-12 12:45:44.260 18587 INFO nova.service [-] Starting cert node (version 2015.1.1-3.el7ost)
2015-11-12 12:45:44.740 18587 INFO oslo_messaging._drivers.impl_rabbit [req-3b78f7d2-260a-4594-ac8a-37821c8857c1 - - - - -] Connecting to AMQP server on 10.211.55.142:5672
2015-11-12 12:45:44.788 18587 INFO oslo_messaging._drivers.impl_rabbit [req-3b78f7d2-260a-4594-ac8a-37821c8857c1 - - - - -] Connected to AMQP server on 10.211.55.142:5672
2015-11-12 16:12:20.174 18587 ERROR nova.servicegroup.drivers.db [req-3b50d3eb-146d-4e02-a0a3-6fd8089c2484 - - - - -] model server went away
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db Traceback (most recent call last):
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/servicegroup/drivers/db.py", line 112, in _report_state
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     service.service_ref, state_catalog)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/conductor/api.py", line 164, in service_update
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return self._manager.service_update(context, service, values)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/utils.py", line 895, in wrapper
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return func(*args, **kwargs)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 142, in inner
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return func(*args, **kwargs)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/conductor/manager.py", line 335, in service_update
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     svc = self.db.service_update(context, service['id'], values)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/db/api.py", line 153, in service_update
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return IMPL.service_update(context, service_id, values)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 271, in wrapped
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return f(*args, **kwargs)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 555, in service_update
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     service_ref = _service_get(context, service_id, session=session)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 458, in _service_get
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     result = query.first()
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2445, in first
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     ret = list(self[0:1])
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2281, in __getitem__
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return list(res)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return self._execute_and_instances(context)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2529, in _execute_and_instances
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     close_with_result=True)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2520, in _connection_from_session
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     **kw)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 882, in connection
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     execution_options=execution_options)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     engine, execution_options)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     conn = bind.contextual_connect()
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     self._wrap_pool_connect(self.pool.connect, None),
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     e, dialect, self)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1401, in _handle_dbapi_exception_noconnection
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     util.raise_from_cause(newraise, exc_info)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     reraise(type(exception), exception, tb=exc_tb)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return fn()
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return _ConnectionFairy._checkout(self)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     fairy = _ConnectionRecord.checkout(pool)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 485, in checkout
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     rec.checkin()
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     compat.reraise(exc_type, exc_value, exc_tb)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 482, in checkout
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     dbapi_connection = rec.get_connection()
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 594, in get_connection
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     self.connection = self.__connect()
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     connection = self.__pool._invoke_creator(self)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return dialect.connect(*cargs, **cparams)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return self.dbapi.connect(*cargs, **cparams)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     return Connection(*args, **kwargs)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db     super(Connection, self).__init__(*args, **kwargs2)
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db DBConnectionError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '10.211.55.142' (101)")
2015-11-12 16:12:20.174 18587 TRACE nova.servicegroup.drivers.db 
2015-11-12 16:12:30.181 18587 ERROR nova.servicegroup.drivers.db [req-3b50d3eb-146d-4e02-a0a3-6fd8089c2484 - - - - -] Recovered model server connection!
2015-11-24 19:13:33.745 1438 INFO nova.openstack.common.periodic_task [-] Skipping periodic task _periodic_update_dns because its interval is negative
2015-11-24 19:13:33.841 1438 WARNING oslo_config.cfg [req-03498f2d-cd9c-48c7-8f0a-6132356a6e0e - - - - -] Option "sql_connection" from group "DEFAULT" is deprecated. Use option "connection" from group "database".
2015-11-24 19:13:33.854 1438 WARNING oslo_config.cfg [req-03498f2d-cd9c-48c7-8f0a-6132356a6e0e - - - - -] Option "lock_path" from group "DEFAULT" is deprecated. Use option "lock_path" from group "oslo_concurrency".
2015-11-24 19:13:33.856 1438 WARNING oslo_config.cfg [req-03498f2d-cd9c-48c7-8f0a-6132356a6e0e - - - - -] Option "url_timeout" from group "neutron" is deprecated. Use option "timeout" from group "neutron".
2015-11-24 19:13:33.874 1438 INFO nova.service [-] Starting cert node (version 2015.1.1-3.el7ost)
2015-11-24 19:13:36.575 1438 WARNING oslo_db.sqlalchemy.session [req-e3d5d7c2-791a-4673-a1ab-870cce206b29 - - - - -] SQL connection failed. -1 attempts left.
2015-11-24 19:13:47.272 1438 INFO oslo_messaging._drivers.impl_rabbit [req-e3d5d7c2-791a-4673-a1ab-870cce206b29 - - - - -] Connecting to AMQP server on 10.211.55.142:5672
2015-11-24 19:13:51.628 1438 INFO oslo_messaging._drivers.impl_rabbit [req-e3d5d7c2-791a-4673-a1ab-870cce206b29 - - - - -] Connected to AMQP server on 10.211.55.142:5672
2015-11-30 18:47:40.580 1438 INFO nova.openstack.common.service [req-03498f2d-cd9c-48c7-8f0a-6132356a6e0e - - - - -] Caught SIGTERM, exiting
2015-11-30 18:47:41.458 1438 ERROR oslo_messaging._drivers.impl_rabbit [-] Failed to consume message from queue: 
2015-11-30 18:47:42.511 2442 INFO nova.openstack.common.periodic_task [-] Skipping periodic task _periodic_update_dns because its interval is negative
2015-11-30 18:47:42.523 2442 WARNING oslo_config.cfg [req-5c779b1c-9b52-4e2c-a8e0-eef772195004 - - - - -] Option "sql_connection" from group "DEFAULT" is deprecated. Use option "connection" from group "database".
2015-11-30 18:47:42.526 2442 WARNING oslo_config.cfg [req-5c779b1c-9b52-4e2c-a8e0-eef772195004 - - - - -] Option "lock_path" from group "DEFAULT" is deprecated. Use option "lock_path" from group "oslo_concurrency".
2015-11-30 18:47:42.528 2442 WARNING oslo_config.cfg [req-5c779b1c-9b52-4e2c-a8e0-eef772195004 - - - - -] Option "url_timeout" from group "neutron" is deprecated. Use option "timeout" from group "neutron".
2015-11-30 18:47:42.529 2442 INFO nova.service [-] Starting cert node (version 2015.1.2-4.el7ost)
2015-11-30 18:47:43.062 2442 INFO oslo_messaging._drivers.impl_rabbit [req-6c9a7555-563a-446b-92f5-2ebe094d7324 - - - - -] Connecting to AMQP server on 10.211.55.142:5672
2015-11-30 18:47:43.123 2442 INFO oslo_messaging._drivers.impl_rabbit [req-6c9a7555-563a-446b-92f5-2ebe094d7324 - - - - -] Connected to AMQP server on 10.211.55.142:5672
2016-01-29 13:13:58.405 2442 INFO nova.openstack.common.service [req-5c779b1c-9b52-4e2c-a8e0-eef772195004 - - - - -] Caught SIGTERM, exiting
2016-01-29 13:13:59.076 2442 ERROR nova.servicegroup.drivers.db [req-e79d7746-a710-4f65-8d88-7e31f9eb10d7 - - - - -] model server went away
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db Traceback (most recent call last):
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/servicegroup/drivers/db.py", line 112, in _report_state
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     service.service_ref, state_catalog)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/conductor/api.py", line 164, in service_update
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return self._manager.service_update(context, service, values)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/utils.py", line 919, in wrapper
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return func(*args, **kwargs)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 142, in inner
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return func(*args, **kwargs)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/conductor/manager.py", line 335, in service_update
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     svc = self.db.service_update(context, service['id'], values)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/db/api.py", line 153, in service_update
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return IMPL.service_update(context, service_id, values)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 271, in wrapped
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return f(*args, **kwargs)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 555, in service_update
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     service_ref = _service_get(context, service_id, session=session)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 458, in _service_get
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     result = query.first()
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2445, in first
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     ret = list(self[0:1])
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2281, in __getitem__
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return list(res)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return self._execute_and_instances(context)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2529, in _execute_and_instances
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     close_with_result=True)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2520, in _connection_from_session
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     **kw)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 882, in connection
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     execution_options=execution_options)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     engine, execution_options)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     conn = bind.contextual_connect()
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2041, in contextual_connect
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     **kwargs)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 92, in __init__
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     self.dispatch.engine_connect(self, self.__branch)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     fn(*args, **kw)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/session.py", line 344, in _connect_ping_listener
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     connection.scalar(select([1]))
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 844, in scalar
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return self.execute(object, *multiparams, **params).scalar()
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return meth(self, multiparams, params)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return connection._execute_clauseelement(self, multiparams, params)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     compiled_sql, distilled_params
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     None, None)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1337, in _handle_dbapi_exception
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     util.raise_from_cause(newraise, exc_info)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     reraise(type(exception), exception, tb=exc_tb)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     conn = self._revalidate_connection()
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 393, in _revalidate_connection
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     self.__connection = self.engine.raw_connection(_connection=self)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     self.pool.unique_connection, _connection)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2080, in _wrap_pool_connect
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     util.reraise(*sys.exc_info())
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return fn()
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return _ConnectionFairy._checkout(self)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     fairy = _ConnectionRecord.checkout(pool)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 485, in checkout
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     rec.checkin()
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     compat.reraise(exc_type, exc_value, exc_tb)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 482, in checkout
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     dbapi_connection = rec.get_connection()
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 563, in get_connection
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     self.connection = self.__connect()
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     connection = self.__pool._invoke_creator(self)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return dialect.connect(*cargs, **cparams)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return self.dbapi.connect(*cargs, **cparams)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     return Connection(*args, **kwargs)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db   File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db     super(Connection, self).__init__(*args, **kwargs2)
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db DBConnectionError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '10.211.55.142' (111)") [SQL: u'SELECT 1']
2016-01-29 13:13:59.076 2442 TRACE nova.servicegroup.drivers.db 
2016-01-29 13:13:59.283 2442 ERROR oslo_messaging._drivers.impl_rabbit [-] Failed to consume message from queue: 
2016-01-29 13:14:33.618 1226 INFO nova.openstack.common.periodic_task [-] Skipping periodic task _periodic_update_dns because its interval is negative
2016-01-29 13:14:33.678 1226 WARNING oslo_config.cfg [req-9821d6ff-e47e-4140-bef9-809cb10bc4d4 - - - - -] Option "sql_connection" from group "DEFAULT" is deprecated. Use option "connection" from group "database".
2016-01-29 13:14:33.681 1226 WARNING oslo_config.cfg [req-9821d6ff-e47e-4140-bef9-809cb10bc4d4 - - - - -] Option "lock_path" from group "DEFAULT" is deprecated. Use option "lock_path" from group "oslo_concurrency".
2016-01-29 13:14:33.682 1226 WARNING oslo_config.cfg [req-9821d6ff-e47e-4140-bef9-809cb10bc4d4 - - - - -] Option "url_timeout" from group "neutron" is deprecated. Use option "timeout" from group "neutron".
2016-01-29 13:14:33.743 1226 INFO nova.service [-] Starting cert node (version 2015.1.2-4.el7ost)
2016-01-29 13:14:35.692 1226 WARNING oslo_db.sqlalchemy.session [req-692a0a96-1be3-4eec-8df9-84a314d3c722 - - - - -] SQL connection failed. -1 attempts left.
2016-01-29 13:14:45.970 1226 INFO oslo_messaging._drivers.impl_rabbit [req-692a0a96-1be3-4eec-8df9-84a314d3c722 - - - - -] Connecting to AMQP server on 10.211.55.142:5672
2016-01-29 13:14:50.437 1226 INFO oslo_messaging._drivers.impl_rabbit [req-692a0a96-1be3-4eec-8df9-84a314d3c722 - - - - -] Connected to AMQP server on 10.211.55.142:5672
